# Generated by Django 5.2.7 on 2025-10-09 21:12

from django.db import migrations


def set_new_building_flag(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Flat.objects.filter(construction_year__gte=2015).update(new_building=True)
    Flat.objects.filter(construction_year__lte=2015).update(new_building=False)
    Flat.objects.filter(construction_year__isnull=True).update(
        new_building=False)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_flat_new_building'),
    ]

    operations = [
        migrations.RunPython(set_new_building_flag)
    ]
