# Generated by Django 5.2.7 on 2025-10-14 11:00

from django.db import migrations
import phonenumbers


def make_pure_phone(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all().iterator():
        if not flat.owners_phonenumber:
            continue
        parsed_phone = phonenumbers.parse(flat.owners_phonenumber, "RU")
        if phonenumbers.is_valid_number(parsed_phone):
            formatted_phone = phonenumbers.format_number(
                parsed_phone, phonenumbers.PhoneNumberFormat.E164)
            flat.owner_pure_phone = formatted_phone
        else:
            flat.owner_pure_phone = None

        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_flat_owner_pure_phone'),
    ]

    operations = [
        migrations.RunPython(make_pure_phone)
    ]
