# Generated by Django 5.2.7 on 2025-10-16 23:02

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_auto_20251015_2110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='flats',
            new_name='flat',
        ),
        migrations.AlterField(
            model_name='owner',
            name='phonenumber',
            field=models.CharField(db_index=True, max_length=20, verbose_name='Номер владельца'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='pure_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, db_index=True, max_length=128, null=True, region=None, verbose_name='Нормализированный номер владельца'),
        ),
    ]
