# Generated by Django 5.2.7 on 2025-10-16 23:04

from django.db import migrations


def link_flats_and_owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')

    for flat_obj in Flat.objects.all():
        owner, created = Owner.objects.get_or_create(
            full_name=flat_obj.owner,
            phonenumber=flat_obj.owners_phonenumber,
            pure_phone=flat_obj.owner_pure_phone
        )

        owner.flat.add(flat_obj)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_rename_flats_owner_flat_alter_owner_phonenumber_and_more'),
    ]

    operations = [
        migrations.RunPython(link_flats_and_owners)
    ]
