# Generated by Django 5.2.7 on 2025-10-21 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0015_alter_flat_new_building'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='user',
            new_name='complainant',
        ),
    ]
