# Generated by Django 5.2.7 on 2025-10-21 09:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0016_rename_user_complaint_complainant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='complainant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints_made', to=settings.AUTH_USER_MODEL, verbose_name='Кто жаловался'),
        ),
    ]
